/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import control.AdminController;
import control.FacturaController;
import control.MedicoController;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Especialidad;
import model.Factura;
import model.Medico;
import model.PacienteLLBN;

/**
 *
 * @author Usuario
 */
public class FrmFacturasmedicas extends javax.swing.JInternalFrame {
         private MedicoController datosmedico;
          private AdminController datos;
                 private FacturaController datosController;

       
    public FrmFacturasmedicas() {
        initComponents();
        datosController = new FacturaController();
        datos = new AdminController();
        datosmedico = new MedicoController();
         DefaultListModel<String> listModel = new DefaultListModel<>();
        jlistp.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlistp = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btneliminar = new javax.swing.JButton();
        btnlista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(520, 490));
        setPreferredSize(new java.awt.Dimension(520, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 20, 280));

        jlistp.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistpMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jlistp);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 480, 320));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FACTURAS MEDICAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        btneliminar.setText("Eliminar factura");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        btnlista.setText("Ver llista de facturas");
        btnlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistaActionPerformed(evt);
            }
        });
        jPanel2.add(btnlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 520, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    
    
    
    private void jlistpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistpMouseClicked
        // Verifica si el clic fue en un ítem de la lista
        if (evt.getClickCount() == 1) {
            int index = jlistp.locationToIndex(evt.getPoint());
            if (index >= 0) {
                DefaultListModel<String> model = (DefaultListModel<String>) jlistp.getModel();
                String selectedItem = model.getElementAt(index);

                String[] parts = selectedItem.split(", ");
                String cedula = parts[0].split(": ")[1];
                String nombre = parts[1].split(": ")[1];
                String apellido = parts[2].split(": ")[1];
                int edad = Integer.parseInt(parts[3].split(": ")[1]);
                LocalDate fechaNac = LocalDate.parse(parts[4].split(": ")[1]);

              
            }
        }
    }//GEN-LAST:event_jlistpMouseClicked

    private int extractNroFactura(String item) {
        try {
            
            String[] parts = item.split(",");  // Divide el texto en partes usando la coma como delimitador
            if (parts.length > 0) {
                // Extrae la parte que contiene el número de factura y quita espacios adicionales
                String nroFacturaString = parts[0].trim().split(":")[1].trim();
                return Integer.parseInt(nroFacturaString);
            }
        } catch (Exception e) {
            // Maneja cualquier excepción y muestra un mensaje de error
            System.err.println("Error al extraer el número de factura: " + e.getMessage());
        }
        // etorna un valor por defecto en caso de error
        return -1;
    }
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
         // Obtener el índice seleccionado
        int selectedIndex = jlistp.getSelectedIndex();

        if (selectedIndex != -1) {
            DefaultListModel<String> model = (DefaultListModel<String>) jlistp.getModel();

            String selectedItem = model.getElementAt(selectedIndex);
            int nroFactura = extractNroFactura(selectedItem);

            // Eliminar la factura
            boolean eliminado = datosController.eliminarFactura(nroFactura);

            if (eliminado) {
                // Actualizar la lista después de la eliminación
                model.remove(selectedIndex);
                JOptionPane.showMessageDialog(this, "Factura eliminada exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la factura.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una factura para eliminar.");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void actualizarListaFacturas(List<Factura> facturas) {
    if (jlistp.getModel() instanceof DefaultListModel) {
        DefaultListModel<String> model = (DefaultListModel<String>) jlistp.getModel();
        model.clear(); // Limpiar la lista

        for (Factura factura : facturas) {
            String item = String.format("Nro Factura: %d, Paciente CI: %s , Fecha: %s  , "
                    + "Descripción: %s   , Especialidad ID: %d   , Médico ID: %d  , Total: %.2f",
                factura.getNroFactura(), factura.getPaciente_ci(), factura.getFecha().toString(),
                factura.getDescripcion_consulta(), 
                factura.getEspecialidad_id(), factura.getMedico_id(), factura.getTotal());
            model.addElement(item);
        }
    } else {
        System.err.println("Error del JList .");
    }
}
    
    private void btnlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistaActionPerformed
        try {
            FacturaController facturaController = new FacturaController(); 
            List<Factura> facturas = facturaController.obtenerTodasFacturas();
            actualizarListaFacturas(facturas);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al obtener facturas: " + 
                    ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnlistaActionPerformed

   
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFacturasmedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFacturasmedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFacturasmedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFacturasmedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFacturasmedicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlista;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> jlistp;
    // End of variables declaration//GEN-END:variables
}
