/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import control.MedicoController;
import control.PacienteController;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.AtencionMedica;
import model.Farmacos;
import model.HistorialPaciente;
import model.Medico;
import model.PacienteLLBN;
import model.Receta;

/**
 *
 * @author Usuario
 */
public class FrmMedico extends javax.swing.JFrame {

        private PacienteController datospaciente;
        private String nombremed;
        private String cedulamed;
        private MedicoController medicoc;

         
    public FrmMedico() {
        initComponents();
        datospaciente = new PacienteController();
        medicoc = new MedicoController();

    }
    
     // Constructor con parámetros
    public FrmMedico(String nombreCompleto, String cedula) {
        initComponents();
        datospaciente = new PacienteController();
        medicoc = new MedicoController();
        nombremed = nombreCompleto;
        cedulamed = cedula;
        actualizarLabels();
    }
    
    

    public String getRecetaContent() {
        return textReceta.getText();
    }
    
    private void actualizarLabels() {
        if (lblmedico != null) {
            lblmedico.setText(nombremed);
        }
       
    }
    
    private void buscarPacientePorCedula() {
         String cedula = txtCedulaP.getText().trim();
    try {
        PacienteLLBN paciente = datospaciente.buscarPacientePorCedula(cedula);
        if (paciente != null) {
            txtNombreP.setText(paciente.getNombre() + " " + paciente.getApellido());
        } else {
            
            txtNombreP.setText(""); // Limpiar el campo si no se encuentra el paciente
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al buscar paciente");
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnGenerarReporteMedico = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dtcFechaAtencion = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarMedicamento = new javax.swing.JButton();
        txtCedulaP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textDiagnostico2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        txtdosis = new javax.swing.JTextField();
        txtNombreMedicamento1 = new javax.swing.JTextField();
        txtdias = new javax.swing.JTextField();
        txtunidades = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textReceta = new javax.swing.JTextArea();
        lblNombreMedico = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lblmedico = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnRecetaMedica = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnHistorialmedico = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtsintomas = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(112, 183, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atencion Medica");

        btnCerrar.setBackground(new java.awt.Color(255, 204, 204));
        btnCerrar.setForeground(new java.awt.Color(255, 102, 102));
        btnCerrar.setText("Cerrar sesion");
        btnCerrar.setToolTipText("");
        btnCerrar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCerrar.setBorderPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCerrar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 680, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerarReporteMedico.setBackground(new java.awt.Color(153, 204, 255));
        btnGenerarReporteMedico.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnGenerarReporteMedico.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerarReporteMedico.setText("Generar  Atencion Medica");
        btnGenerarReporteMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteMedicoActionPerformed(evt);
            }
        });
        jPanel4.add(btnGenerarReporteMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha de atencion:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));
        jPanel4.add(dtcFechaAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Sintomas");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Diagnostico");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        btnAgregarMedicamento.setBackground(new java.awt.Color(147, 168, 210));
        btnAgregarMedicamento.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAgregarMedicamento.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarMedicamento.setText("Agregar");
        btnAgregarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedicamentoActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 307, 130, -1));

        txtCedulaP.setForeground(new java.awt.Color(0, 0, 0));
        txtCedulaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCedulaPMouseEntered(evt);
            }
        });
        jPanel4.add(txtCedulaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 150, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cedula");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Visualizacion:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 370, 20));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 670, 220));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("DATOS DEL PACIENTE");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(134, 155, 198));
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 50, 4));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("            Medicamento");
        jPanel1.add(jLabel2);

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("        Unidades");
        jPanel1.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("         Dosis        ");
        jPanel1.add(jLabel14);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("                 Dias");
        jPanel1.add(jLabel5);

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 650, 30));

        textDiagnostico2.setColumns(20);
        textDiagnostico2.setRows(5);
        jScrollPane4.setViewportView(textDiagnostico2);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 260, 80));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdosis.setForeground(new java.awt.Color(0, 0, 0));
        txtdosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdosisActionPerformed(evt);
            }
        });
        jPanel2.add(txtdosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 250, 38));

        txtNombreMedicamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMedicamento1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreMedicamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 38));

        txtdias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiasActionPerformed(evt);
            }
        });
        jPanel2.add(txtdias, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 110, 38));

        txtunidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunidadesActionPerformed(evt);
            }
        });
        jPanel2.add(txtunidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 120, 38));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 650, 70));

        textReceta.setBackground(new java.awt.Color(255, 255, 255));
        textReceta.setColumns(20);
        textReceta.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        textReceta.setForeground(new java.awt.Color(51, 51, 51));
        textReceta.setRows(5);
        textReceta.setEnabled(false);
        jScrollPane1.setViewportView(textReceta);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 510, 80));

        lblNombreMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMedico.setText("Medico a cargo:");
        jPanel4.add(lblNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 90, 20));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 370, 120));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 300, 120));

        lblmedico.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        lblmedico.setForeground(new java.awt.Color(0, 0, 0));
        lblmedico.setText("__________");
        jPanel4.add(lblmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, 20));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Paciente");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtNombreP.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, -1));

        jPanel5.setBackground(new java.awt.Color(209, 231, 253));

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("RECETA");

        btnRecetaMedica.setBackground(new java.awt.Color(255, 255, 255));
        btnRecetaMedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/certificado medico.png"))); // NOI18N
        btnRecetaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecetaMedicaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Generar doc. de receta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(619, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRecetaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnRecetaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 670, 230));

        btnHistorialmedico.setText("Ver historial medico");
        btnHistorialmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialmedicoActionPerformed(evt);
            }
        });
        jPanel4.add(btnHistorialmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        txtsintomas.setColumns(20);
        txtsintomas.setRows(5);
        jScrollPane3.setViewportView(txtsintomas);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 90, 260, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose(); // Cierra la ventana actual
        FrmLogin login = new FrmLogin();
        login.setVisible(true); // Abre la ventana de login
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtdosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdosisActionPerformed

    private void txtNombreMedicamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMedicamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMedicamento1ActionPerformed

    private void txtdiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiasActionPerformed

    private void txtunidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunidadesActionPerformed

    private void txtCedulaPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaPMouseEntered
        String cedula = txtCedulaP.getText().trim();
        if (cedula.length() == 10) { // Asumiendo que la cédula tiene 10 dígitos
            buscarPacientePorCedula();
        } else if (cedula.isEmpty()) {
            txtNombreP.setText(""); // Limpiar el campo de nombre si la cédula está vacía
        }
    }//GEN-LAST:event_txtCedulaPMouseEntered

    private void btnAgregarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedicamentoActionPerformed
          // Obtener y validar datos de los campos de texto
            String nombreMedicamento = txtNombreMedicamento1.getText().trim();
            String unidadesStr = txtunidades.getText().trim();
            String dosis = txtdosis.getText().trim();
            String diasStr = txtdias.getText().trim();

            if (nombreMedicamento.isEmpty() || unidadesStr.isEmpty() || dosis.isEmpty() || diasStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos de la receta.");
                return;
            }

            int unidades, dias;
            try {
                unidades = Integer.parseInt(unidadesStr);
                dias = Integer.parseInt(diasStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos para unidades y días.");
                return;
            }
            // Obtener el id_atencion
            int idAtencion = medicoc.obtenerUltimoIdAtencion();

            // Ajustar id_atencion si es 0
            if (idAtencion <= 0) {
                idAtencion = 1;
            }
            
            // Se debe obtener el id_farmaco usando el nombre del medicamento
            Farmacos farmaco =  medicoc.buscarFarmacoPorNombre(nombreMedicamento);
            Receta receta;

            if (farmaco != null) {
                // Si se encontró el farmaco
                receta = new Receta(0, new AtencionMedica(idAtencion), farmaco,nombreMedicamento,unidades, dosis, dias);
                textReceta.append("Medicamento: " + farmaco.getNombreMedicamento() + ", Unidades: " + unidades + ", Dosis: " + dosis + ", Días: " + dias + "\n");
            } else {
                // Si no se encontró el farmaco, usar medicamento por nombre
                receta = new Receta(0, new AtencionMedica(idAtencion), null, nombreMedicamento, unidades, dosis, dias);
                textReceta.append("Medicamento: " + nombreMedicamento + ", Unidades: " + unidades + ", Dosis: " + dosis + ", Días: " + dias + "\n");
            }
            
            // Registrar la receta en la base de datos
            boolean registrado = medicoc.registrarReceta(receta, idAtencion);

            if (registrado) {
                JOptionPane.showMessageDialog(this, "Receta registrada con éxito.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar la receta.");
            }
    }//GEN-LAST:event_btnAgregarMedicamentoActionPerformed

    private void btnGenerarReporteMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteMedicoActionPerformed
         String cedulaPaciente = txtCedulaP.getText().trim();
        String nombrePaciente = txtNombreP.getText().trim();
        String sintomas = txtsintomas.getText().trim();
        String diagnostico = textDiagnostico2.getText().trim();
        Date fechaAtencion = dtcFechaAtencion.getDate();

        if (cedulaPaciente.isEmpty() || nombrePaciente.isEmpty() || sintomas.isEmpty() || 
             diagnostico.isEmpty() || fechaAtencion == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos de la atención médica.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Crear objeto AtencionMedica
            AtencionMedica atencion = new AtencionMedica();
            atencion.setPaciente(new PacienteLLBN());
            atencion.getPaciente().setCi(cedulaPaciente);
            atencion.setMedico(new Medico()); 
            atencion.getMedico().setCi(cedulamed); // Usando la cédula del médico guardada
            atencion.setFecha_atencion(fechaAtencion.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            atencion.setSintomas(sintomas);
            atencion.setDiagnostico(diagnostico);

            // Registrar la atención médica
            boolean registrado = medicoc.registrarAtencionMedica(atencion);
            if (registrado) {
                JOptionPane.showMessageDialog(this, "Atención médica registrada con éxito.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar la atención médica.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Formato de temperatura o pulso incorrecto.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar la atención médica.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarReporteMedicoActionPerformed

    private void btnHistorialmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialmedicoActionPerformed
         String cedula = txtCedulaP.getText().trim();
        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la cédula del paciente.");
            return;
        }

        HistorialPaciente historial = medicoc.obtenerHistorialAtenciones(cedula);

        if (historial == null || historial.getPaciente() == null) {
            JOptionPane.showMessageDialog(this, "El paciente no tiene istorial medico");
            return;
        }

        PacienteLLBN paciente = historial.getPaciente();
        StringBuilder mensaje = new StringBuilder();
        mensaje.append("Datos del Paciente:\n");
        mensaje.append("Cédula: ").append(paciente.getCi()).append("\n");
        mensaje.append("Nombre: ").append(paciente.getNombre()).append("\n");
        mensaje.append("Apellido: ").append(paciente.getApellido()).append("\n");
        mensaje.append("Edad: ").append(paciente.getEdad()).append("\n");
       
        mensaje.append("Historial de Atenciones:\n");

        for (AtencionMedica atencion : historial.getAtenciones()) {
            mensaje.append("Fecha: ").append(atencion.getFecha_atencion()).append("\n");
            mensaje.append("Médico tratante: ").append(atencion.getMedico().getNombre()).append(" ").append(atencion.getMedico().getApellido()).append("\n");
            mensaje.append("Tipo de conulta:: ").append(atencion.getMedico().getEspecialidad().getNombre()).append("\n");
            mensaje.append("Diagnóstico: ").append(atencion.getDiagnostico()).append("\n\n");
        }

        JTextArea textArea = new JTextArea(mensaje.toString());
        textArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(500, 300));

        JOptionPane.showMessageDialog(this, scrollPane, "Historial del Paciente", JOptionPane.PLAIN_MESSAGE, null);
    }//GEN-LAST:event_btnHistorialmedicoActionPerformed

    private void btnRecetaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecetaMedicaActionPerformed
         String nombreMedico = lblmedico.getText();
        String nombrePaciente = txtNombreP.getText();
        String fecha = (dtcFechaAtencion.getDate() != null) ? 
            new SimpleDateFormat("dd/MM/yyyy").format(dtcFechaAtencion.getDate()) : "";
        String receta = getRecetaContent();

        RecetaMedica recetaMedica = new RecetaMedica(nombreMedico, nombrePaciente, fecha, receta);
        recetaMedica.setVisible(true);
    }//GEN-LAST:event_btnRecetaMedicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMedicamento;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerarReporteMedico;
    private javax.swing.JButton btnHistorialmedico;
    private javax.swing.JButton btnRecetaMedica;
    private com.toedter.calendar.JDateChooser dtcFechaAtencion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JLabel lblmedico;
    private javax.swing.JTextArea textDiagnostico2;
    private javax.swing.JTextArea textReceta;
    private javax.swing.JTextField txtCedulaP;
    private javax.swing.JTextField txtNombreMedicamento1;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtdias;
    private javax.swing.JTextField txtdosis;
    private javax.swing.JTextArea txtsintomas;
    private javax.swing.JTextField txtunidades;
    // End of variables declaration//GEN-END:variables
}
